config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :articles
    resources :lists

    match 'login' => 'sessions#new', :via => :get
    match 'login' => 'sessions#create', :via => :post
    match 'logout' => 'sessions#destroy', :via => :delete
    
    root :to => 'articles#index'
  end

  scope "(:locale)", locale: /en|ko/ do
    namespace :api do 
      get 'articles/:permalink/lists/:listPermalink' => 'articles#permalink'
      get 'articles/:permalink' => 'articles#permalink'
      get 'lists/:permalink' => 'lists#permalink'
      get 'welcome' => 'api#welcome'
    end

    get '/articles/:articlePermalink/lists/:listPermalink' => 'articles#show', as: 'article_list_permalink'
    get '/articles/:articlePermalink' => 'articles#show', as: 'article_permalink'
    get '/lists/:listPermalink' => 'lists#show', as: 'list_permalink'
    root :to => 'welcome#index'
  end


end

app/models/list.rb
class List < ApplicationRecord
  def list_conv_to_json
    {
      id: self.id,
      title_ko: self.title_ko,
      title_en: self.title_en,
      permalink: self.permalink
    }
  end

  def conv_to_json
    {
      id: self.id,
      title_ko: self.title_ko,
      title_en: self.title_en,
      permalink: self.permalink,
      description_ko: self.description_ko,
      description_en: self.description_en,
      react_classname: self.react_classname
    }
  end
end

app/controllers/admin/lists_controller.rb
class Admin::ListsController < Admin::AdminController
  def index
    @lists = List.order("idx ASC")
  end

  def new
    @list = List.new

  end

  def create
    @list = List.new(params.require(:list).permit(
      :title_en,
      :title_ko,
      :permalink,
      :react_classname,
      :description_ko,
      :description_en))
   
    
    if @list.save
      flash[:notice] = 'Successfully updated.'
      redirect_to edit_admin_list_path(@list)
    else

      flash[:alert] = "#{@list.errors.messages.values.join(' ')}"
      redirect_to request.referer
    end

  end
  
  def edit
    @list = List.find params[:id]
  end

  def update
    @list = List.find params[:id]
   
    
    if @list.update_attributes(params.require(:list).permit(
      :title_en,
      :title_ko,
      :permalink,
      :idx,
      :react_classname,
      :description_ko,
      :description_en))

      flash[:notice] = 'Successfully updated.'
      redirect_to request.referer
    else

      flash[:alert] = "#{@list.errors.messages.values.join(' ')}"
      redirect_to request.referer
    end

  end


  def destroy
    @list= List.find params[:id]
    @list.destroy
    redirect_to admin_lists_path, :notice => 'Successfully destroyed'
  end

end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  def permalink
    @list = List.where(permalink: params[:permalink]).first

    render json: {success: true, list: @list.conv_to_json, locale: I18n.locale }
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
    @list = List.where(permalink: params[:listPermalink]).first
  end
end

app/views/admin/lists/_form.html.erb
<%= form_for [:admin, @list], :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :title_ko, '국문 제목', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :title_ko, :class => 'form-control', :placeholder => '국문 제목' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title_en, '영문 제목', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :title_en, :class => 'form-control', :placeholder => '영문 제목' %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :permalink, '퍼머링크', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :permalink, :class => 'form-control', :placeholder => '퍼머링크' %>
    </div>
  </div>
   <div class="form-group">
    <%= f.label :react_classname, '리액트 클래스이름(있을 경우 클래스 호출로 대체)', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :react_classname,  :class => 'form-control', :placeholder => '리액트 클래스이름' %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :description_ko, '국문 설명', :class => 'col-md-2 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description_ko, :class => 'form-control', :placeholder => '마크다운', :rows => 40, :cols => 120 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description_en, '영문 설명', :class => 'col-md-2 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description_en, :class => 'form-control', :placeholder => '마크다운', :rows => 40, :cols => 120 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>


<script>
  $(document).ready(function(e){

    $("textarea").each(function() {
      var editor = CodeMirror.fromTextArea($(this).get(0), {
        lineNumbers: true,
        mode: "htmlmixed",
        theme: "base16-dark",
        lineWrapping: true
      });
    });

  });

</script>

app/views/admin/lists/_idx_update_form.html.erb
<%= form_for [:admin, list], :html => {:class => 'form-inline'} do |f| %>
  <div class="form-group">
     <%= f.text_field :idx, :class => 'form-control', style: 'width:40px' %>
  </div>
<% end %>

app/views/admin/lists/_tab.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li <%= 'class=active' if params[:action] == 'index' and params[:controller] == 'admin/lists' %>>
    <%= link_to "All Lists(#{List.count})", admin_lists_path %>
  </li>
  <% if @list.present? and not @list.new_record? %>
  <li class="active">
    <%= link_to "#{@list.title_ko} / #{@list.title_en}", edit_admin_list_path(@list) %>
  </li>
  <% elsif @list.present? and @list.new_record? %>
  <li class="active">
    <%= link_to "New List", "javascript:void(0);" %>
  </li>
  <% end %>
</ul>

app/views/admin/lists/edit.html.erb
<%= render 'tab' %>

<h3>
  Edit List
</h3>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/lists/index.html.erb
<%= render 'tab' %>
<h3> 
  All Lists
</h3>

<table class="table table-striped">
  <tr>
    <th>
      #
    </th>
    <th>
      idx
    </th>
    <th>
      Title
    </th>
    <th>
      Permalink
    </th>
    <th>
      Delete
    </th>
  </tr>
  <% @lists.each do |list| %>
  <tr>
    <td><%= list.id %></td>
    <td>
      <%= render partial: 'idx_update_form', locals: {list: list} %>
    </td>
    <td><%= link_to "#{list.title_ko} / #{list.title_en}", edit_admin_list_path(list) %></td>
    <td><%= list.permalink %></td>
    <td>
      <%= link_to 'Delete', admin_list_path(list), data: {method: 'delete', confirm: 'are you sure?'} %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'New List', new_admin_list_path, :class => 'btn btn-default' %>

app/views/admin/lists/new.html.erb
<%= render 'tab' %>

<h3>
  New List
</h3>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>