config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :articles
    resources :lists

    match 'login' => 'sessions#new', :via => :get
    match 'login' => 'sessions#create', :via => :post
    match 'logout' => 'sessions#destroy', :via => :delete
    
    root :to => 'articles#index'
  end

  scope "(:locale)", locale: /en|ko/ do
    namespace :api do 
      get 'articles/:permalink/lists/:listPermalink' => 'articles#permalink'
      get 'articles/:permalink' => 'articles#permalink'
      get 'lists/:permalink' => 'lists#permalink'
      get 'welcome' => 'api#welcome'
    end

    get '/articles/:articlePermalink/lists/:listPermalink' => 'articles#show', as: 'article_list_permalink'
    get '/articles/:articlePermalink' => 'articles#show', as: 'article_permalink'
    get '/lists/:listPermalink' => 'lists#show', as: 'list_permalink'
    root :to => 'welcome#index'
  end


end

app/models/article.rb
class Article < ApplicationRecord

  def list_conv_to_json
    {
      id: self.id,
      author_ko: self.author_ko,
      author_en: self.author_en,
      title_ko: self.title_ko,
      title_en: self.title_en,
      permalink: self.permalink
    }
  end

  def conv_to_json
    {
      id: self.id,
      author_ko: self.author_ko,
      author_en: self.author_en,
      title_ko: self.title_ko,
      title_en: self.title_en,
      permalink: self.permalink,
      react_classname: self.react_classname,
      background_color: self.background_color,
      color: self.color,
      description_ko: self.description_ko,
      description_en: self.description_en,
      init_list_permalink: self.init_list_permalink
    }
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  def index
    @articles = Article.order("idx ASC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(
      :title_ko,
      :title_en,
      :description_ko,
      :description_en,
      :author_ko,
      :author_en,
      :init_list_permalink,
      :permalink,
      :react_classname,
      :background_color,
      :color))
   
    
    if @article.save
      flash[:notice] = 'Successfully updated.'
      redirect_to edit_admin_article_path(@article)
    else

      flash[:alert] = "#{@article.errors.messages.values.join(' ')}"
      redirect_to request.referer
    end

  end
  
  def edit
    @article = Article.find params[:id]
  end

  def update
    @article = Article.find params[:id]
    
    if @article.update_attributes(params.require(:article).permit(
      :title_ko,
      :title_en,
      :permalink,
      :description_ko,
      :description_en,
      :author_ko,
      :author_en,
      :idx,
      :react_classname,
      :init_list_permalink,
      :background_color,
      :color))
      flash[:notice] = 'Successfully updated.'
      redirect_to request.referer
    else

      flash[:alert] = "#{@article.errors.messages.values.join(' ')}"
      redirect_to request.referer
    end

  end


  def destroy
    @article= Article.find params[:id]
    @article.destroy
    redirect_to admin_articles_path, :notice => 'Successfully destroyed'
  end

end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  def permalink
    @article = Article.where(permalink: params[:permalink]).first
    
    result = {success: true, article: @article.conv_to_json, locale: I18n.locale }
    

    if params[:listPermalink].present?
      @list = List.where(permalink: params[:listPermalink]).first
      result[:list] = @list.conv_to_json
    end


    render json: result
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.where(permalink: params[:articlePermalink]).first
    @list = List.where(permalink: params[:listPermalink]).first

    if @list.present?
      render layout: 'articles_lists'
    else
      render layout: 'articles'
    end
  end
end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article], :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :title_ko, '국문 제목', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :title_ko, :class => 'form-control', :placeholder => '국문 제목' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title_en, '영문 제목', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :title_en, :class => 'form-control', :placeholder => '영문 제목' %>
    </div>
  </div>
   <div class="form-group">
    <%= f.label :permalink, '퍼머링크', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :permalink, :class => 'form-control', :placeholder => '퍼머링크' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :init_list_permalink, '같이 뜰 목록 퍼머링크', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :init_list_permalink,  :class => 'form-control', :placeholder => '같이뜰 목록 퍼머링크' %>
    </div>
  </div>
   <div class="form-group">
    <%= f.label :react_classname, '리액트 클래스이름(있을 경우 클래스 호출로 대체)', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :react_classname,  :class => 'form-control', :placeholder => '리액트 클래스이름' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :author_ko, '저자 이름(국문)', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :author_ko, :class => 'form-control', :placeholder => '저자 이름(국문)' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :author_en, '저자 이름(영문)', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :author_en, :class => 'form-control', :placeholder => '저자 이름(영문)' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :color, '글씨 색깔', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :color, :class => 'form-control', :placeholder => '글씨 색깔' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :background_color, '배경 색깔', :class => 'col-md-2 control-label' %>
    <div class="col-md-5">
      <%= f.text_field :background_color, :class => 'form-control', :placeholder => '배경 색깔' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description_ko, '국문 설명', :class => 'col-md-2 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description_ko, :class => 'tinymce', :placeholder => 'html', :rows => 40, :cols => 150 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description_en, '영문 설명', :class => 'col-md-2 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description_en, :class => 'tinymce', :placeholder => 'html', :rows => 40, :cols => 120 %>
    </div>
  </div>





  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>


<script>
  $(document).ready(function(e){
    $(".jsontinymce").each(function() {
      var editor = CodeMirror.fromTextArea($(this).get(0), {
        lineNumbers: true,
        mode: "javascript",
        theme: "base16-dark",
        lineWrapping: true
      });

      editor.setSize(600, 300);
    });

    $(".tinymce").each(function() {
      var editor = CodeMirror.fromTextArea($(this).get(0), {
        lineNumbers: true,
        mode: "htmlmixed",
        theme: "base16-dark",
        lineWrapping: true
      });
    });

  });

</script>

app/views/admin/articles/_idx_update_form.html.erb
<%= form_for [:admin, article], :html => {:class => 'form-inline'} do |f| %>
  <div class="form-group">
     <%= f.text_field :idx, :class => 'form-control', style: 'width:40px' %>
  </div>
<% end %>

app/views/admin/articles/_tab.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li <%= 'class=active' if params[:action] == 'index' and params[:controller] == 'admin/articles' %>>
    <%= link_to "All Articles(#{Article.count})", admin_articles_path %>
  </li>
  <% if @article.present? and not @article.new_record? %>
  <li class="active">
    <%= link_to "#{@article.title_ko} / #{@article.title_en}", edit_admin_article_path(@article) %>
  </li>
  <% elsif @article.present? and @article.new_record? %>
  <li class="active">
    <%= link_to "New Article", "javascript:void(0);" %>
  </li>
  <% end %>
</ul>

app/views/admin/articles/edit.html.erb
<%= render 'tab' %>

<h3>
  Edit Article
</h3>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/articles/index.html.erb
<%= render 'tab' %>
<h3> 
  All Articles
</h3>

<table class="table table-striped">
  <tr>
    <th>
      #
    </th>
    <th>
      idx
    </th>
    <th>
      Title
    </th>
    <th>
      Author
    </th>
    <th>
      Delete
    </th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.id %></td>
    <td>
      <%= render partial: 'idx_update_form', locals: {article: article} %>
    </td>
    <td><%= link_to "#{article.title_ko} / #{article.title_en}", edit_admin_article_path(article) %></td>
    <td><%= "#{article.author_ko} / #{article.author_en}" %></td>
    <td>
      <%= link_to 'Delete', admin_article_path(article), data: {method: 'delete', confirm: 'are you sure?'} %> 
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'New Article', new_admin_article_path, :class => 'btn btn-default' %>

app/views/admin/articles/new.html.erb
<%= render 'tab' %>

<h3>
  New Article
</h3>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>