config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :articles
    resources :lists

    match 'login' => 'sessions#new', :via => :get
    match 'login' => 'sessions#create', :via => :post
    match 'logout' => 'sessions#destroy', :via => :delete
    
    root :to => 'articles#index'
  end

  scope "(:locale)", locale: /en|ko/ do
    namespace :api do 
      get 'articles/:permalink/lists/:listPermalink' => 'articles#permalink'
      get 'articles/:permalink' => 'articles#permalink'
      get 'lists/:permalink' => 'lists#permalink'
      get 'welcome' => 'api#welcome'
    end

    get '/articles/:articlePermalink/lists/:listPermalink' => 'articles#show', as: 'article_list_permalink'
    get '/articles/:articlePermalink' => 'articles#show', as: 'article_permalink'
    get '/lists/:listPermalink' => 'lists#show', as: 'list_permalink'
    root :to => 'welcome#index'
  end


end

app/views/layouts/_admin_header.html.erb
 <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to '한국 인터넷 관광안내서', admin_root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= 'class=active' if params[:controller] == 'admin/users'  %>>
          <%= link_to "Admin(#{User.count})", admin_users_path %>
        </li>
        <li <%= 'class=active' if params[:controller] == 'admin/articles'  %>>
          <%= link_to "Articles(#{Article.count})", admin_articles_path %>
        </li>
        <li <%= 'class=active' if params[:controller] == 'admin/lists'  %>>
          <%= link_to "Lists(#{List.count})", admin_lists_path %>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Sign out', admin_logout_path, method: :delete %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>한국 인터넷 관광 안내서 어드민</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

  <%= stylesheet_link_tag    "admin", media: "all"  %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/admin_header' %>
  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>한국 인터넷 관광 안내서 / Korean Internet Tour Guide</title>
    <%= csrf_meta_tags %>

    <meta property="og:site_name" content="한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/> 
    <meta property="og:description" content="한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/> 
    <meta name="description" content="한국 인터넷 관광 안내서 / Korean Internet Tour Guide" />

    <meta name="title" content="한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>
    <meta property="og:title" content="한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>

    <link rel="canonical" href="<%= root_url %>">
    <meta property="og:url" content="<%= root_url %>">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="<%= I18n.locale == "ko" ? "ko_KR" : "en_US" %>">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"></meta>

    <meta property="og:image" content="<%= asset_url("og.png") %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:type" content="image/png" />
    
        <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_url("apple-icon-57x57.png") %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_url("apple-icon-60x60.png") %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_url("apple-icon-72x72.png") %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_url("apple-icon-76x76.png") %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_url("apple-icon-114x114.png") %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_url("apple-icon-120x120.png") %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_url("apple-icon-144x144.png") %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_url("apple-icon-152x152.png") %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url("apple-icon-180x180.png") %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_url("android-icon-192x192.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url("favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= asset_url("favicon-96x96.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url("favicon-16x16.png") %>">
    <link rel="manifest" href="<%= asset_url("manifest.json") %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= asset_url("ms-icon-144x144.png") %>">
    <meta name="theme-color" content="#ffffff">

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id="root">
    </div>
    <%= javascript_include_tag *webpack_asset_paths("application") %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-83519105-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{@article.title_ko} / #{@article.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide</title>
    <%= csrf_meta_tags %>

    <meta property="og:site_name" content="<%= "#{@article.title_ko} / #{@article.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/> 
    <meta property="og:description" content="<%= truncate(strip_tags(@article.try("description_#{I18n.locale}")), length: 100) %>"/> 
    <meta name="description" content="<%= truncate(strip_tags(@article.try("description_#{I18n.locale}")), length: 100) %>" />

    <meta name="title" content="<%= "#{@article.title_ko} / #{@article.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>
    <meta property="og:title" content="<%= "#{@article.title_ko} / #{@article.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>

    <link rel="canonical" href="<%= article_permalink_url(@article.permalink) %>">
    <meta property="og:url" content="<%= article_permalink_url(@article.permalink) %>">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="<%= I18n.locale == "ko" ? "ko_KR" : "en_US" %>">

    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"></meta>

        <meta property="og:image" content="<%= asset_url("og.png") %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:type" content="image/png" />
        <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_url("apple-icon-57x57.png") %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_url("apple-icon-60x60.png") %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_url("apple-icon-72x72.png") %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_url("apple-icon-76x76.png") %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_url("apple-icon-114x114.png") %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_url("apple-icon-120x120.png") %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_url("apple-icon-144x144.png") %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_url("apple-icon-152x152.png") %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url("apple-icon-180x180.png") %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_url("android-icon-192x192.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url("favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= asset_url("favicon-96x96.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url("favicon-16x16.png") %>">
    <link rel="manifest" href="<%= asset_url("manifest.json") %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= asset_url("ms-icon-144x144.png") %>">
    <meta name="theme-color" content="#ffffff">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id="root">
    </div>
    <%= javascript_include_tag *webpack_asset_paths("application") %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-83519105-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/layouts/articles_lists.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{@article.title_ko} / #{@article.title_en}" %> + <%= "#{@list.title_ko} / #{@list.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide</title>
    <%= csrf_meta_tags %>

    <meta property="og:site_name" content="한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/> 
    <meta property="og:description" content="<%= truncate(strip_tags(@article.try("description_#{I18n.locale}")), length: 150) %>"/> 
    <meta name="description" content="<%= truncate(strip_tags(@article.try("description_#{I18n.locale}")), length: 150) %>" />

    <meta name="title" content="<%= "#{@article.title_ko} / #{@article.title_en}" %> + <%= "#{@list.title_ko} / #{@list.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>
    <meta property="og:title" content="<%= "#{@article.title_ko} / #{@article.title_en}" %> + <%= "#{@list.title_ko} / #{@list.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>

    <link rel="canonical" href="<%= article_permalink_url(@article.permalink) %>">
    <meta property="og:url" content="<%= article_permalink_url(@article.permalink) %>">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="<%= I18n.locale == "ko" ? "ko_KR" : "en_US" %>">

    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"></meta>

        <meta property="og:image" content="<%= asset_url("og.png") %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:type" content="image/png" />
        <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_url("apple-icon-57x57.png") %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_url("apple-icon-60x60.png") %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_url("apple-icon-72x72.png") %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_url("apple-icon-76x76.png") %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_url("apple-icon-114x114.png") %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_url("apple-icon-120x120.png") %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_url("apple-icon-144x144.png") %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_url("apple-icon-152x152.png") %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url("apple-icon-180x180.png") %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_url("android-icon-192x192.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url("favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= asset_url("favicon-96x96.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url("favicon-16x16.png") %>">
    <link rel="manifest" href="<%= asset_url("manifest.json") %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= asset_url("ms-icon-144x144.png") %>">
    <meta name="theme-color" content="#ffffff">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id="root">
    </div>
    <%= javascript_include_tag *webpack_asset_paths("application") %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-83519105-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/layouts/lists.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{@list.title_ko} / #{@list.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide</title>
    <%= csrf_meta_tags %>

    <meta property="og:site_name" content=":: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/> 
    <meta property="og:description" content="<%= truncate(@list.try("description_#{I18n.locale}"), length: 100) %>"/> 
    <meta name="description" content="<%= truncate(@list.try("description_#{I18n.locale}"), length: 100) %>" />

    <meta name="title" content="<%= "#{@list.title_ko} / #{@list.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>
    <meta property="og:title" content="<%= "#{@list.title_ko} / #{@list.title_en}" %> :: 한국 인터넷 관광 안내서 / Korean Internet Tour Guide"/>

    <link rel="canonical" href="<%= list_permalink_url(@list.permalink) %>">
    <meta property="og:url" content="<%= list_permalink_url(@list.permalink) %>">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="<%= I18n.locale == "ko" ? "ko_KR" : "en_US" %>">

    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"></meta>
    <meta property="og:image" content="<%= asset_url("og.png") %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:type" content="image/png" />
        <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_url("apple-icon-57x57.png") %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_url("apple-icon-60x60.png") %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_url("apple-icon-72x72.png") %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_url("apple-icon-76x76.png") %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_url("apple-icon-114x114.png") %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_url("apple-icon-120x120.png") %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_url("apple-icon-144x144.png") %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_url("apple-icon-152x152.png") %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url("apple-icon-180x180.png") %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_url("android-icon-192x192.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url("favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= asset_url("favicon-96x96.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url("favicon-16x16.png") %>">
    <link rel="manifest" href="<%= asset_url("manifest.json") %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= asset_url("ms-icon-144x144.png") %>">
    <meta name="theme-color" content="#ffffff">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id="root">
    </div>
    <%= javascript_include_tag *webpack_asset_paths("application") %>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83519105-1', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>